// Generated from a 4096x2048 HEVC Main, 8-bit 4:2:0, Level 5 single-frame stream.
// The canary only identifies whether WebCodecs exposes planar output.
const CANARY_BASE64 = [
    'AAAAAUABDAH//wFgAAADAJAAAAMAAAMAlroCQAAAAAFCAQEBYAAAAwCQAAADAAADAJagAIAIAIAWW6SkwvAWgIAAAAMAgAAADwQAAAABRAHAc8GJ',
    'AAABKAGsIQIBp44oYYYIIH3nnnXXXXXXXXXXXXXHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHHIBv//xlzRWZ5zJgAAAwAAAwAAAwAAAwAAAwAA',
    'AwAAAwAAAwAAAwABwxUdv5zJgAAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAWEBS+cyYAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAABDw',
    'GHWUAAADAAADAAADAAADAAADAAADAAADAAADAAADAAAFjBpUAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAQkAAAMAAAMAAAMAAAMAAAMA',
    'AAMAAAMAAAMAAAMAAAMAABUwAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAAERAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAA2Y',
    'AAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAHfAAAADAAADAAADAAADAAADAAADAAADAAADAAADAAADAmoAAAMAAAMAAAMAAAMAAAMAAAMA',
    'AAMAAAMAAAMAAAzIAAADAAADAAADAAADAAADAAADAAADAAADAAADAAAuIAAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAkYAAAAMAAAMAAAMA',
    'AAMAAAMAAAMAAAMAAAMAAAMAAWkAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAA1IAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMABxQAAAMA',
    'AAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMADUgAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAGBAAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMA',
    'JeAAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAOuAAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAUUAAAAMAAAMAAAMAAAMAAAMAAAMAAAMA',
    'AAMAAAMAbMAAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAjoAAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAsIAAAAMAAAMAAAMAAAMAAAMA',
    'AAMAAAMAAAMAAAMA2YAAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMA+YAAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMBHQAAAwAAAwAAAwAA',
    'AwAAAwAAAwAAAwAAAwAAAwE9AAADAAADAAADAAADAAADAAADAAADAAADAAADAVsAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMBcQAAAwAAAwAA',
    'AwAAAwAAAwAAAwAAAwAAAwAAAwGBAAADAAADAAADAAADAAADAAADAAADAAADAAADAY8AAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMBmQAAAwAA',
    'AwAAAwAAAwAAAwAAAwAAAwAAAwAAAwGhAAADAAADAAADAAADAAADAAADAAADAAADAAADAaEAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMBqQAA',
    'AwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwGpAAADAAADAAADAAADAAADAAADAAADAAADAAADAakAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMB',
    'qQAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwGpAAADAAADAAADAAADAAADAAADAAADAAADAAADAakAAAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMA',
    'AAMBqQAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwGpAAADAAADAAADAAADAAADAAADAAADAAADAAADAakAAAMAAAMAAAMAAAMAAAMAAAMAAAMA',
    'AAMAAAMBqQAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwGpAAADAAADAAADAAADAAADAAADAAADAAADAAADAakAAAMAAAMAAAMAAAMAAAMAAAMA',
    'AAMAAAMAAAMBqQAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwGpAAADAAADAAADAAADAAADAAADAAADAAADAAADAakAAAMAAAMAAAMAAAMAAAMA',
    'AAMAAAMAAAMAAAMBqQAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwGpAAADAAADAAADAAADAAADAAADAAADAAADAAADAakAAAMAAAMAAAMAAAMA',
    'AAMAAAMAAAMAAAMAAAMBqQAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwGpAAADAAADAAADAAADAAADAAADAAADAAADAAADAakAAAMAAAMAAAMA',
    'AAMAAAMAAAMAAAMAAAMAAAMBqQAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwGpAAADAAADAAADAAADAAADAAADAAADAAADAAADAakAAAMAAAMA',
    'AAMAAAMAAAMAAAMAAAMAAAMAAAMBqQAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwGpAAADAAADAAADAAADAAADAAADAAADAAADAAADAakAAAMA',
    'AAMAAAMAAAMAAAMAAAMAAAMAAAMAAAMBqQAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwAAAwGrAA==',
].join('');

let canaryBytes = null;

export function getWebCodecsCapabilityCanary() {
    if (canaryBytes) return canaryBytes;

    const binary = atob(CANARY_BASE64);
    canaryBytes = new Uint8Array(binary.length);
    for (let index = 0; index < binary.length; index++) {
        canaryBytes[index] = binary.charCodeAt(index);
    }
    return canaryBytes;
}

export const WEB_CODECS_CANARY_DESCRIPTOR = Object.freeze({
    codecId: 2,
    frameWidth: 4096,
    frameHeight: 2048,
    frameCount: 1
});
